### PR TITLE
Add AviSynth support

### PR DESCRIPTION
**Pull request by Asd-g**

### CODE REVIEW

**Comment by quietvoid** [comment]
In the current state of the changes, it's not building on Linux anymore.
[ninja.log](https://github.com/user-attachments/files/17267407/ninja.log)

**Comment by Asd-g** [comment]
Thanks. I will take a look at it later.

**Comment by Asd-g** [comment]
Adding the header [here](https://github.com/Asd-g/bore/blob/master/src/common.h#L20)  `#include <stddef.h>` fixes the build for me under Debian bookworm (GCC 12.2.0) - [ninja1.log](https://github.com/user-attachments/files/17270149/ninja1.log)
What compiler and version do you use?

**Comment by quietvoid** [comment]
Yes that works here.
There are many unused param warnings but it builds.

**Comment by Asd-g** [comment]
Either warnings (now only [two function pointers](https://github.com/Asd-g/bore/blob/master/src/common.h#L42-L43) are used for [all processing functions](https://github.com/Asd-g/bore/blob/master/src/common.h#L46-L63)) or more function pointers have to be added for every processing function with different parameters.

**Pull request merged**
